python main.py \
  --data_dir ./garbage-dataset \
  --model_type basic \
  --epochs 200 \
  --batch_size 16 \
  --learning_rate 0.01 \
  --weight_decay 0.0001 \
  --optimizer sgd \
  --save_dir ./garbage-classification-basic-wo-aug \